version: "3.9"
services:
  api:
    container_name: dev1
    image: registry.gitlab.com/tolgakaraoglan/krgln:latest
    #build: ./dev1/
    networks:
      - backend
    volumes:
      - type: volume
        source: dev1-vol
        target: /app
  nodered:
    container_name: nodered
    #image: "nodered/node-red"
    build: ./nodered/
    networks:
      - backend
    environment:
      - INFLUXDB_TOKEN=krglntoken
    ports:
      - "1880:1880"
    volumes:
      - type: volume
        source: nodered-vol
        target: /data
  influxdb:
    container_name: influxdb
    build: ./influxdb/
    networks:
      - backend
    #image: influxdb
    volumes:
      - type: volume
        source: influxdb-vol
        target: /var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=krgln
      - DOCKER_INFLUXDB_INIT_PASSWORD=krgln135
      - DOCKER_INFLUXDB_INIT_ORG=krgln
      - DOCKER_INFLUXDB_INIT_BUCKET=krglnbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=krglntoken
  grafana:
    container_name: grafana
    build: ./grafana/
    #image: grafana/grafana
    networks:
      - frontend
      - backend
      - db
    ports: 
      - "3000:3000"
    volumes:
      - type: volume
        source: grafana-vol
        target: /var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=krgln
      - GF_SECURITY_ADMIN_PASSWORD=krgln
      - INFLUXDB_TOKEN=krglntoken
      - POSTGRES_USER=krgln
      - POSTGRES_DB=krglndb
      - POSTGRES_PASSWORD=krgln135
  postgres:
    container_name: postgres
    build: ./postgres/
    networks:
      - db
    volumes:
      - type: volume
        source: postgres-vol
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=krgln
      - POSTGRES_PASSWORD=krgln135
      - POSTGRES_DB=krglndb
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    networks:
      - backend
      - db
    environment:
      - PGRST_DB_URI=postgres://krgln:krgln135@postgres:5432/krglndb
      - PGRST_DB_ANON_ROLE=krgln
      - PGRST_DB_SCHEMA=public
volumes:
  dev1-vol: {}
  nodered-vol: {}
  influxdb-vol: {}
  grafana-vol: {}
  postgres-vol: {}
  
networks:
  frontend: {}
  backend: {}
  db: {}